
# Training params
num_epochs: 20000
batch_size: 1
learning_rate: 0.0002
max_grad_norm: 1.0

save_step: 50000
save_dir: '.'

# Data params
preemph_coef: 0.97
sample_rate: 22050
hop_samples: 300
crop_mel_frames: 30
n_fft: 2048
n_mels: 128

data_path: 'data/LJSpeech-1.1'
manifest_path: 'data/ljspeech_manifest.csv'

# Model params
noise_schedule_start: 0.000001
noise_schedule_end: 0.01
noise_schedule_S: 1000

is_large: True

dblock:
    init_conv_channels: 32
    init_conv_kernels: 5
    hidden_size: [128, 128, 256, 512]
    factor: [2, 2, 3, 5]
    kernel_size: [3, 3, 3]
    dilations: [1, 2, 4]

film:
    output_size: [128, 128, 256, 512, 512]
    kernel_size: [3, 3, 3, 3, 3]

ublock:
    hidden_size: [512, 512, 256, 128, 128]
    factor: [5, 5, 3, 2, 2]
    dilation: [
        [1, 2, 1, 2],
        [1, 2, 1, 2],
        [1, 2, 4, 8],
        [1, 2, 4, 8],
        [1, 2, 4, 8]]
    kernel_size: 3

first_conv:
    hidden_size: 768
    kernel_size: 3

last_conv:
    kernel_size: 3
